# CI/bootstrap runner for Blender action-potential integration v04.
#
# Blender resolves paths beginning with // relative to the currently loaded
# .blend file. In headless CI the startup file has no project path, so the
# standalone v03 builder could resolve //action_potential_models_v03.blend to
# the filesystem root. Save a tiny bootstrap .blend next to the scripts first,
# run the normal v04 generator, then apply headless-safe presentation fixes and
# re-save the render-ready v04 scene.

from pathlib import Path
import runpy

import bpy

HERE = Path(__file__).resolve().parent
BOOTSTRAP_BLEND = HERE / "_ci_bootstrap_action_potential.blend"
V04_SCRIPT = HERE / "action_potential_video_v04.py"
FINAL_BLEND = HERE / "action_potential_pokrovsky_v04.blend"

bpy.ops.wm.save_as_mainfile(filepath=str(BOOTSTRAP_BLEND))
print("ACTION_POTENTIAL_CI_BOOTSTRAP", BOOTSTRAP_BLEND)
runpy.run_path(str(V04_SCRIPT), run_name="__main__")

# The integrated layout spans farther to the right than the original model-pack
# camera because the scientific Vm graph is present. A slightly wider lens keeps
# the graph panel, membrane edge and labels inside the 16:9 safe frame even at
# the closest phase-emphasis keyframes.
cam = bpy.context.scene.camera
if cam is not None:
    cam.data.lens = 42.0

# Ion labels are children of scaled UV spheres. Without compensation the sphere
# radius scales the text a second time and pushes it too close to the sphere
# centre. Undo only that inherited scale and place the glyph on the camera-facing
# surface. Parent animation still hides/reveals the whole ion and label together.
ION_BODIES = {"Na⁺", "K⁺", "Cl⁻"}
fixed_labels = 0
for obj in bpy.data.objects:
    if obj.type != 'FONT' or obj.parent is None or obj.data.body not in ION_BODIES:
        continue

    parent = obj.parent
    base_scale = 0.0
    if parent.animation_data and parent.animation_data.action:
        for fc in parent.animation_data.action.fcurves:
            if fc.data_path == "scale":
                for kp in fc.keyframe_points:
                    base_scale = max(base_scale, abs(float(kp.co[1])))
    if base_scale <= 1e-6:
        base_scale = max(abs(float(v)) for v in parent.scale)
    if base_scale <= 1e-6:
        continue

    inv = 1.0 / base_scale
    obj.scale = (inv, inv, inv)
    obj.location.x = 0.0
    obj.location.y = -1.05
    obj.location.z = 0.0
    fixed_labels += 1

# Save over the render-ready scene generated by v04; the intermediate v03 pack
# remains reusable and independent.
bpy.ops.wm.save_as_mainfile(filepath=str(FINAL_BLEND))
print("ACTION_POTENTIAL_V04_POSTPROCESS_OK", "labels=", fixed_labels, "lens=", 42.0)
